name: Playwright Tests

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      #- uses: actions/setup-node@v4
      #  with: 
      #    cache: 'npm'
      #    node-version: '22'
      - run: npm ci 
      - run: PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install # --with-deps # <- not needed for self-hosted
      - run: PLAYWRIGHT_BROWSERS_PATH=0 npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
