name: Tests

on: [workflow_dispatch]

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: 
          cache: 'npm'
          node-version: '22'
      - run: npm ci
      - run: npx -y @lhci/cli autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        continue-on-error: true # let the github status show failure

  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: 
          cache: 'npm'
          node-version: '22'
      - run: npm ci 
      - run: PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install --with-deps
      - run: PLAYWRIGHT_BROWSERS_PATH=0 npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
